name: Build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  push_bot:
    name: Build, tag, and push container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Docker Registry
        uses: azure/docker-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PAT }}
          login-server: "docker.pkg.github.com"

      - name: Build, tag, and push container
        run: |
          docker build --build-arg VERSION=${{ github.sha }} -t docker.pkg.github.com/knibble/DogeBot/dogebot:latest .
          docker push docker.pkg.github.com/knibble/DogeBot/dogebot:latest
